### ISSUE TITLE
Submit using POST instead of GET

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion-capme#14]
I'm not a web developer, I'll freely admit, but my understanding is that, if a browser is submitting anything sensitive such as a username or password, the normal method used is POST rather than GET.  That keeps the sensitive data out of the access logs and the browser's URL.  Is there any reason POST can't be used here when submitting a request?

Any web developers have the expertise and time to propose something or generate a pull request?

Could HTTP BasicAuth be used for SSO between ELSA, squert, and capme to avoid this issue altogether?  I realize that makes user management a little more difficult for sguil, but I suspect most users only ever create and use a single account anyway...

**Comment by dougburks** [comment]
Hi petiepooo,

You're correct that submitting credentials via GET is a dirty hack and a bad idea from a security standpoint.  That's why we've never configured those credentials to be sent by default.  A user would have to manually configure that option _if_ they're willing to accept the risk.

Backstory: this "feature" comes out of the legacy of Snorby submitting credentials to OpenFPC using GET.  CapMe was developed to be "OpenFPC-compatible" so that it could be an alternative source for Snorby to get full packet capture.  

Moving forward, a short term goal would be to add session support to CapME (potentially merging CapME into Squert) such that you would authenticate the first time you pivot to pcap and then leave your session open to continue pivoting to pcap later.

A longer term goal would be SSO or perhaps even merging all web interfaces into one grand unified interface.

If anybody would like to step up and volunteer, pull requests are always welcome!  :)

**Comment by dougburks** [comment]
I've created a separate issue for adding session support to CapME:
https://github.com/Security-Onion-Solutions/security-onion/issues/871
